Repository MIcQo/galvanico, pull requests merged in 2025-04, with the labels that each got.

#41 fix(db): remove empty line after rollback (closes #37)
  cmd/galvanico-db/migrate.go
  cmd/galvanico-db/rollback.go
Labels: bug, go

#38 Feat/user authorization
  config.example.yaml
  config.schema.json
  go.mod
  go.sum
  internal/auth/auth.go
  internal/auth/auth_test.go
  internal/auth/handler.go
  internal/auth/jwt.go
  internal/auth/jwt_test.go
  internal/broker/nats.go
  internal/config/config.go
  internal/game/user/features.go
  internal/game/user/handlers.go
  internal/game/user/handlers_test.go
  internal/game/user/repository.go
  internal/game/user/resources.go
  internal/game/user/service.go
  internal/game/user/service_test.go
  internal/game/user/user.go
  internal/game/user/username.go
  internal/game/user/username_test.go
  internal/notifications/message.go
  internal/notifications/template.go
  internal/server/server.go
  internal/utils/random.go
  internal/utils/random_test.go
  migrations/20250329214314_create_users_table.up.sql
Labels: enhancement, go

#62 feat(auth): #50 add client for login & registration
  client/bun.lock
  client/e2e/vue.spec.ts
  client/package.json
  client/src/App.vue
  client/src/assets/base.css
  client/src/assets/main.css
  client/src/components/Alert.vue
  client/src/locale/en.ts
  client/src/locale/index.ts
  client/src/locale/sk.ts
  client/src/main.ts
  client/src/router/index.ts
  client/src/services/api.ts
  client/src/services/auth.ts
  client/src/stores/alert.ts
  client/src/views/AboutView.vue
  client/src/views/Auth/Layout.vue
  client/src/views/Auth/Login.vue
  client/src/views/Auth/Register.vue
  client/src/views/Game/IndexView.vue
  client/src/views/Game/Layout.vue
  client/src/views/HomeView.vue
  client/vite.config.ts
  internal/game/user/handlers.go
  internal/server/server.go
Labels: enhancement
